#!/bin/bash
#BSUB -J TMEseg
#BSUB -W 24:00
#BSUB -o /rsrch5/scratch/trans_mol_path/xpan7/pipelines/logs/%J_lsf.out
#BSUB -e /rsrch5/scratch/trans_mol_path/xpan7/pipelines/logs/%J_lsf.err
#BSUB -q medium
#BSUB -n 4
#BSUB -M 16
#BSUB -R rusage[mem=16]
#BSUB -B
#BSUB -N
#BSUB -J "tmeseg[1-120:1]"


module load anaconda3/2023.07-2
eval "$(/risapps/rhel8/anaconda3/2023.07-2/bin/conda shell.bash hook)"  #seadragon2
# eval "$(/risapps/rhel7/anaconda3/2023.07-2/bin/conda shell.bash hook)"     #seadragon1
conda activate /rsrch5/home/trans_mol_path/xpan7/.conda/envs/tfCPU2p5

data_dir=/rsrch5/scratch/trans_mol_path/xpan7/project/tcga_tnbc/til/1_cws_tiling
output_dir=/rsrch5/scratch/trans_mol_path/xpan7/project/tcga_tnbc/tmeseg_tcga20x384finetune/mask_cws_norm
ss1_dir=/rsrch5/scratch/trans_mol_path/xpan7/project/tcga_tnbc/tmeseg_tcga20x384finetune/mask_ss1_norm
file_name_pattern='*.svs'
color_norm=true

# set the color normalization flag, if applicable
if [ "$color_norm" = true ]; then
    color_norm_args=''
else
    color_norm_args='-c'
fi

python main_tme.py -d "$data_dir" -o "$output_dir" -s "$ss1_dir" -p "$file_name_pattern" $color_norm_args -n $((LSB_JOBINDEX-1))
